services:
  api:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    ports:
      - 5432:5432